version: "3.7"

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: R1234r
            MYSQL_DATABASE: todo_db
            MYSQL_USER: insider
            MYSQL_PASSWORD: Insider_1

    myapp:
        image: 954880510467.dkr.ecr.eu-central-1.amazonaws.com/todo-app:main-ddd959b
        restart: always
        depends_on:
            - database
        ports:
            - "80:3333"
